### ISSUE TITLE
Add python 3.8 tests

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#15404]
Python 3.8 should be released soon (~weeks I think) 🎉 . This is a placeholder to remind us to add tests with py3.8 to the testing suite.

**Comment by dhermes** [comment]
Happy to chip in here. Also, would it make sense to release 3.8 wheels for the current release (3.1.1)?

**Comment by QuLogic** [comment]
This is #15451.

**Comment by tacaswell** [comment]
Sorry, I have a longish comment on this written up from yesterday in a computer at work and then things kept lighting on (metaphorical) :fire: 

Pushing on https://github.com/matthew-brett/multibuild/issues/261 to sort out why mac+ py38 is not working (see https://travis-ci.org/MacPython/matplotlib-wheels/jobs/602111497 and https://github.com/MacPython/matplotlib-wheels

**Comment by matthew-brett** [comment]
Tom - I think there are only 10.9 installers for Python 3.8 - so, if you don't have it, you need something like in the build matrix:

```
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.8
        - MB_PYTHON_OSX_VER=10.9
```

See: https://github.com/MacPython/numpy-wheels/blob/master/.travis.yml
