### ISSUE TITLE
[MNT]: Add codespell to pre-commit hooks

### ISSUE THREAD

**Issue by matthewfeickert** [matplotlib/matplotlib#22740]
### Summary

In PR #22733 @QuLogic caught a spelling error of mine (which is great!) but there will inevitably be typos that slip through if only humans are checking. https://github.com/codespell-project/codespell is a really nice way to check for typos and it has a nice pre-commit hook. As Matplotlib [already uses pre-commit](https://github.com/matplotlib/matplotlib/blob/da9533d507c1f06ceee5078c9cbbd99897809d31/.pre-commit-config.yaml) :rocket: (thanks to @ianhi in PR #21583) this would be an easy add. :+1: 

### Proposed fix

Add the following hook (maybe some variations) to [`.pre-commit-config.yaml`](https://github.com/matplotlib/matplotlib/blob/da9533d507c1f06ceee5078c9cbbd99897809d31/.pre-commit-config.yaml)

```yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        files: ^.*\.(py|md|rst|yml)$
```
