### ISSUE TITLE
[MNT]: pytest-testmon for github actions

### ISSUE THREAD

**Issue by Bogusik** [matplotlib/matplotlib#22868]
### Summary

Currently each CI/CD pipeline in "Tests" workflow takes nearly 18 minutes to be finished. "Run pytest" step takes nearly 12 minutes to be finished. In my opinion it takes too long.

### Proposed fix

My proposal is based on using pytest-testmon in GHA. This plugin collects dependencies between tests and all executed code and compares the dependencies against changes. So it could improve times of pipelines.

You could try pytest-testmon to be run within "Tests" workflow just by adding next steps:
```
     - uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: .testmondata
          key: testmon=${{ github.ref_name }}-${{ matrix.python-version }}
          restore-keys: testmon=${{ matrix.python-version }}-main

      - name: Run testmon
        run: |
          ${{ matrix.XVFB_RUN }} python -mpytest -raR -n auto \
            --maxfail=50 --timeout=300 --durations=25 --testmon \
            --log-level=DEBUG --color=yes
```
