### ISSUE TITLE
[Doc]: Easily access kwargs documentation from iPython/Jupyter

### ISSUE THREAD

**Issue by the-guruji** [matplotlib/matplotlib#24489]
### Documentation Link

https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.scatter.html

### Problem

Accessing docstrings via `?` (for example `plt.scatter?` does not enumerate all keyword arguments, but lists where one can find them, for example, for `plt.scatter`,:
```
**kwargs : `~matplotlib.collections.Collection` properties
```
On the online docs, this is a link; however on iPython/Jupyter it is not clear how to access these without adding another import.
 
`plt.xticks` for example, says “`.Text` properties …” so it's a bit clearer that `plt.text?` will show the list of keyword arguments. `plt.plot?` although mentions that `kwargs` come from `.Line2D` also shows all of them in the docstring itself.

### Suggested improvement

I am not familiar enough with the inner workings of matplotlib to be able to provide a proper solution/suggestion for this beyond blind speculation. Maybe it might be possible to somehow sync, for example, the docstrings for `maplotlib.collections.Collection` and `plt.scatter` so that the keywords appear in the docstring (to get something similar to `plt.plot`)? 

Or perhaps, some way to access the keywords for the underlying code without having to do another import and mentioning that in the docstrings for `**kwargs`. Maybe mirror the docstrings from the underlying code and/or combine them in some `plt.doc.scatter` (or `plt.doc.scatter_extra`) so that `plt.doc.scatter?` would show the full list of available keywords and valid values (not sure if this is even desirable)

(Apologies if this seems vague/not well reasoned; it was just a small annoyance that I faced with the docstrings with my specific workflow, which might be fairly typical of someone using Jupyter notebook to make the plot)

**Comment by timhoffm** [comment]
I'm a bit torn here between easily accessible detail and adding too much less relevant information which moves everything else like notes and examples further down.

Anyway, we should pick up a consistent policy. - Could also be that we have it in the docstring (interpolated) but strip it out for sphinx - or make it a dropdown in sphinx.

Semi-OT: I think we have some properties in there which don't work e.g. for https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.bar.html#matplotlib.axes.Axes.bar: `figure`, `xy`, `x`, `y`. If we want to be more precise we could filter them out.

**Comment by timhoffm** [comment]
We by now typically list all the properties:

```
**kwargs : `~matplotlib.collections.PathCollection` properties
    Properties:
    agg_filter: a filter function, which takes a (m, n, 3) float array and a dpi value, and returns a (m, n, 3) array and two offsets from the bottom left corner of the image
    alpha: array-like or float or None
    animated: bool
    antialiased or aa or antialiaseds: bool or list of bools
    array: array-like or None
    capstyle: `.CapStyle` or {'butt', 'projecting', 'round'}
    clim: (vmin: float, vmax: float)
    clip_box: `~matplotlib.transforms.BboxBase` or None
    clip_on: bool
```
